
module.exports = function(vid){
return {
    info: get(null, vid),
    accelerometer: get('accelerometer', vid),
    airbags: get('airbags', vid, 'airbags'),
    pressure: get('barometer', vid, 'pressure'),
    battery: get('battery', vid),
    charge: get('charge', vid, 'state'),
    chargeLimit: get('charge/limit', vid),
    chargeSchedule: get('charge/schedule', vid),
    climate: get('climate', vid),
    collisionSensor: get('collisionSensor', vid, 'isTriggered'),
    heading: get('compass', vid, 'heading'),
    cruiseControl: get('cruise_control', vid),
    dimensions: get('dimension', vid),
    doors: get('doors', vid, 'doors'),
    childLocks: get('safety_locks', vid, 'safetyLocks'),
    driveMode: get('drive_mode', vid, 'mode'),
    engine: get('engine', vid, 'state'),
    engineCoolant: get('engine/coolant', vid),
    hood: get('engine/hood', vid, 'isOpen'),
    engineOil: get('engine/oil', vid),
    throttlePosition: get('engine/throttle', vid, 'percentOpen'),
    fuel: get('fuel', vid),
    headlights: get('lights/headlight', vid, 'state'),
    interiorLights: get('lights/interior', vid, 'lights'),
    turnIndicator: get('lights/turn_indicator', vid, 'state'),
    location: get('location', vid),
    mirrors: get('mirrors', vid, 'mirrors'),
    odometer: get('odometer', vid, 'distance'),
    tripOdometers: get('odometer/trip', vid, 'trips'),
    acceleratorPosition: get('pedals/accelerator', vid, 'percentDepressed'),
    brakePedalPosition: get('pedals/brake', vid, 'percentDepressed'),
    raining: get('rain_sensor', vid, 'isRaining'),
    seats: get('seats', vid, 'seats'),
    locked: get('security', vid, 'isLocked'),
    sliBattery: get('sli_battery', vid),
    speedometer: get('speedometer', vid, 'speed'),
    steeringWheel: get('steering_wheel', vid),
    sunroof: get('sunroof', vid),
    tachometer: get('tachometer', vid, 'speed'),
    interiorTemperature: get('thermistors/interior', vid, 'temperature'),
    tirePressures: get('tires', vid, 'tires'),
    transmission: get('transmission', vid),
    transmissionFluid: get('transmission/fluid', vid),
    frontTrunkOpen: get('trunks/front', vid, 'isOpen'),
    rearTrunkOpen: get('trunks/rear', vid, 'isOpen'),
    vin: get('vin', vid, 'vin'),
    washerFluidRemaining: get('washer_fluid', vid, 'percentRemaining'),
    wheelDiameters: get('wheels', vid, 'wheels'),
    wheelSpeeds: get('wheels/speed', vid, 'wheelSpeed'),
    windows: get('windows', vid, 'windows'),
    yawRate: get('yaw', vid, 'rate'),
    startCharging: action('charge', vid, 'START'),
    stopCharging: action('charge', vid, 'STOP'),
    enableChargeLimit: action('charge/limit', vid, 'ENABLE', 'limit'),
    disableChargeLimit: action('charge/limit', vid, 'DISABLE'),
    enableChargeSchedule: action('charge/schedule', vid, 'ENABLE', 'startTime'),
    disableChargeSchedule: action('charge/schedule', vid, 'DISABLE'),
    startClimate: action('climate', vid, 'START', 'temperature'),
    stopClimate: action('climate', vid, 'STOP'),
    startEngine: action('engine', vid, 'START'),
    stopEngine: action('engine', vid, 'STOP'),
    turnEngineOn: action('engine', vid, 'ON'),
    turnEngineAC1: action('engine', vid, 'ACCESSORY_1'),
    turnEngineAC2: action('engine', vid, 'ACCESSORY_2'),
    openHood: action('engine/hood', vid, 'OPEN'),
    closeHood: action('engine/hood', vid, 'CLOSE'),
    honkHorn: action('horn', vid, 'HONK'),
    flashHeadlights: action('lights/headlights', vid, 'FLASH'),
    adjustMirrors: action('mirrors', vid, 'TILT', 'mirrors'),
    startPanic: action('panic', vid, 'START'),
    stopPanic: action('panic', vid, 'STOP'),
    openChargePort: action('ports/charge', vid, 'OPEN'),
    closeChargePort: action('ports/charge', vid, 'CLOSE'),
    openFuelPort: action('ports/fuel', vid, 'OPEN'),
    closeFuelPort: action('ports/fuel', vid, 'CLOSE'),
    lock: action('security', vid, 'LOCK'),
    unlock: action('security', vid, 'UNLOCK'),
    openSunroof: action('sunroof', vid, 'OPEN', 'percentOpen'),
    ventSunroof: action('sunroof', vid, 'VENT'),
    closeSunroof: action('sunroof', vid, 'CLOSE'),
    openFrontTrunk: action('trunks/front', vid, 'OPEN'),
    closeFrontTrunk: action('trunks/front', vid, 'CLOSE'),
    openRearTrunk: action('trunks/rear', vid, 'OPEN'),
    closeRearTrunk: action('trunks/rear', vid, 'CLOSE'),
    openWindows: action('windows', vid, 'OPEN', 'windows'),
    closeWindows: action('windows', vid, 'CLOSE', 'windows'),
    lockWindows: action('windows', vid, 'LOCK', 'windows'),
    unlockWindows: action('windows', vid, 'UNLOCK', 'windows')
}
}