var methods = require('./vehicle_methods')
var _ = require('lodash')
var util = require('./util')
module.exports = function(token, vid){
    var vehicle = {};
    _.each(methods, function(config, method){
        config = _.extend({vid: vid, token: token}, config);
        vehicle[method] = util[config.type](config);
    })
    return vehicle
}
/*
    return {
    info: util.get(token, null, vid),
    accelerometer: util.get(token, 'accelerometer', vid),
    airbags: util.get(token, 'airbags', vid, 'airbags'),
    pressure: util.get(token, 'barometer', vid, 'pressure'),
    battery: util.get(token, 'battery', vid),
    charge: util.get(token, 'charge', vid, 'state'),
    chargeLimit: util.get(token, 'charge/limit', vid),
    chargeSchedule: util.get(token, 'charge/schedule', vid),
    climate: util.get(token, 'climate', vid),
    collisionSensor: util.get(token, 'collisionSensor', vid, 'isTriggered'),
    heading: util.get(token, 'compass', vid, 'heading'),
    cruiseControl: util.get(token, 'cruise_control', vid),
    dimensions: util.get(token, 'dimension', vid),
    doors: util.get(token, 'doors', vid, 'doors'),
    childLocks: util.get(token, 'safety_locks', vid, 'safetyLocks'),
    driveMode: util.get(token, 'drive_mode', vid, 'mode'),
    engine: util.get(token, 'engine', vid, 'state'),
    engineCoolant: util.get(token, 'engine/coolant', vid),
    hood: util.get(token, 'engine/hood', vid, 'isOpen'),
    engineOil: util.get(token, 'engine/oil', vid),
    throttlePosition: util.get(token, 'engine/throttle', vid, 'percentOpen'),
    fuel: util.get(token, 'fuel', vid),
    headlights: util.get(token, 'lights/headlight', vid, 'state'),
    interiorLights: util.get(token, 'lights/interior', vid, 'lights'),
    turnIndicator: util.get(token, 'lights/turn_indicator', vid, 'state'),
    location: util.get(token, 'location', vid),
    mirrors: util.get(token, 'mirrors', vid, 'mirrors'),
    odometer: util.get(token, 'odometer', vid, 'distance'),
    tripOdometers: util.get(token, 'odometer/trip', vid, 'trips'),
    acceleratorPosition: util.get(token, 'pedals/accelerator', vid, 'percentDepressed'),
    brakePedalPosition: util.get(token, 'pedals/brake', vid, 'percentDepressed'),
    raining: util.get(token, 'rain_sensor', vid, 'isRaining'),
    seats: util.get(token, 'seats', vid, 'seats'),
    locked: util.get(token, 'security', vid, 'isLocked'),
    sliBattery: util.get(token, 'sli_battery', vid),
    speedometer: util.get(token, 'speedometer', vid, 'speed'),
    steeringWheel: util.get(token, 'steering_wheel', vid),
    sunroof: util.get(token, 'sunroof', vid),
    tachometer: util.get(token, 'tachometer', vid, 'speed'),
    interiorTemperature: util.get(token, 'thermistors/interior', vid, 'temperature'),
    tirePressures: util.get(token, 'tires', vid, 'tires'),
    transmission: util.get(token, 'transmission', vid),
    transmissionFluid: util.get(token, 'transmission/fluid', vid),
    frontTrunkOpen: util.get(token, 'trunks/front', vid, 'isOpen'),
    rearTrunkOpen: util.get(token, 'trunks/rear', vid, 'isOpen'),
    vin: util.get(token, 'vin', vid, 'vin'),
    washerFluidRemaining: util.get(token, 'washer_fluid', vid, 'percentRemaining'),
    wheelDiameters: util.get(token, 'wheels', vid, 'wheels'),
    wheelSpeeds: util.get(token, 'wheels/speed', vid, 'wheelSpeed'),
    windows: util.get(token, 'windows', vid, 'windows'),
    yawRate: util.get(token, 'yaw', vid, 'rate'),

    startCharging: util.action(token, 'charge', vid, 'START'),
    stopCharging: util.action(token, 'charge', vid, 'STOP'),
    enableChargeLimit: util.action(token, 'charge/limit', vid, 'ENABLE', 'limit'),
    disableChargeLimit: util.action(token, 'charge/limit', vid, 'DISABLE'),
    enableChargeSchedule: util.action(token, 'charge/schedule', vid, 'ENABLE', 'startTime'),
    disableChargeSchedule: util.action(token, 'charge/schedule', vid, 'DISABLE'),
    startClimate: util.action(token, 'climate', vid, 'START', 'temperature'),
    stopClimate: util.action(token, 'climate', vid, 'STOP'),
    startEngine: util.action(token, 'engine', vid, 'START'),
    stopEngine: util.action(token, 'engine', vid, 'STOP'),
    turnEngineOn: util.action(token, 'engine', vid, 'ON'),
    turnEngineAC1: util.action(token, 'engine', vid, 'ACCESSORY_1'),
    turnEngineAC2: util.action(token, 'engine', vid, 'ACCESSORY_2'),
    openHood: util.action(token, 'engine/hood', vid, 'OPEN'),
    closeHood: util.action(token, 'engine/hood', vid, 'CLOSE'),
    honkHorn: util.action(token, 'horn', vid, 'HONK'),
    flashHeadlights: util.action(token, 'lights/headlights', vid, 'FLASH'),
    adjustMirrors: util.action(token, 'mirrors', vid, 'TILT', 'mirrors'),
    startPanic: util.action(token, 'panic', vid, 'START'),
    stopPanic: util.action(token, 'panic', vid, 'STOP'),
    openChargePort: util.action(token, 'ports/charge', vid, 'OPEN'),
    closeChargePort: util.action(token, 'ports/charge', vid, 'CLOSE'),
    openFuelPort: util.action(token, 'ports/fuel', vid, 'OPEN'),
    closeFuelPort: util.action(token, 'ports/fuel', vid, 'CLOSE'),
    lock: util.action(token, 'security', vid, 'LOCK'),
    unlock: util.action(token, 'security', vid, 'UNLOCK'),
    openSunroof: util.action(token, 'sunroof', vid, 'OPEN', 'percentOpen'),
    ventSunroof: util.action(token, 'sunroof', vid, 'VENT'),
    closeSunroof: util.action(token, 'sunroof', vid, 'CLOSE'),
    openFrontTrunk: util.action(token, 'trunks/front', vid, 'OPEN'),
    closeFrontTrunk: util.action(token, 'trunks/front', vid, 'CLOSE'),
    openRearTrunk: util.action(token, 'trunks/rear', vid, 'OPEN'),
    closeRearTrunk: util.action(token, 'trunks/rear', vid, 'CLOSE'),
    openWindows: util.action(token, 'windows', vid, 'OPEN', 'windows'),
    closeWindows: util.action(token, 'windows', vid, 'CLOSE', 'windows'),
    lockWindows: util.action(token, 'windows', vid, 'LOCK', 'windows'),
    unlockWindows: util.action(token, 'windows', vid, 'UNLOCK', 'windows')
    }
}
*/